Listen __PORT__

<VirtualHost *:__PORT__>
    ServerName smcr_cloud
    DocumentRoot /var/www/html

    <Directory /var/www/html>
        Options -Indexes +FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    # Sessões PHP em volume persistente
    php_value session.save_path /data/php_sessions

    ErrorLog /dev/stderr
    CustomLog /dev/stdout combined
</VirtualHost>
