name: SMCR Cloud HA
version: "1.0.23"
slug: smcr_cloud_ha
description: Gerenciamento centralizado de dispositivos SMCR (ESP32) com suporte a MQTT e HA Discovery.
url: https://github.com/rede-analista/SMCR_HA
arch:
  - amd64
  - aarch64
startup: application
boot: auto
host_network: true
ingress: true
ingress_port: 8765
ports:
  8765/tcp: 8765
ports_description:
  8765/tcp: Interface web do SMCR Cloud
map:
  - data:rw
options:
  port: 8765
  db_password: "smcr_secret_2024"
  admin_user: "admin"
  admin_password: "admin123"
  reset_on_start: false
schema:
  port: port
  db_password: str
  admin_user: str
  admin_password: str
  reset_on_start: bool
panel_icon: mdi:router-wireless
panel_title: SMCR Cloud HA